name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"  
      
      - name: Prepare cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Create env file
        run: |
          touch .env
          echo JWT_SECRET="github_actions_tests" >> .env
          echo SALT=12 >> .env
          echo HOST_EMAIL=smtp.mailtrap.io >> .env
          echo PORT_EMAIL=2525 >> .env
          echo USER_EMAIL=7f0c0a4ac5db4f >> .env
          echo PWD_EMAIL=a84f7c9bab16c5 >> .env
          echo FROM_EMAIL=garaujo_dev@dev.com >> .env
          cat .env
      
      - name: Install dependencies and run tests
        run: |
          npm ci
          npm run test:coveralls 
      
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
